[package]
name = "vulkan_rust"
version = "0.1.0"
authors = ["nicholas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erupt = "0.17.1"
winit = "0.24.0"
structopt = "0.3.21"
ultraviolet = "0.7.5"